development:
  secret_key_base: '507062badc90667464c933deb3427939d157f590ca7046f023cd3ea2a0f19fd38684f8f4d04fede28b3c60e23445609f93f35ef186c341db939b7abbcd8ffcad'

test:
  secret_key_base: '507062badc90667464c933deb3427939d157f590ca7046f023cd3ea2a0f19fd38684f8f4d04fede28b3c60e23445609f93f35ef186c341db939b7abbcd8ffcad'

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
